In [2]:
###조건문 3_1_1

A = 1
if(A == 1):
    print(A)

1


In [3]:
if (A == 1):
    print("a")

a


In [7]:
loss = input("Now Loss : ")
loss = float(loss)
#input은 무조건 문자열메서드임 float이든 int로 꼭 바꿔주자!
if loss <= 5:
    print('learning Succsful.')
elif loss <= 10:
    print('learning Failed.')
elif loss <= 15:
    print('leaning Failed. Adjust learning Rate.')
else:
    print('Model Init')

Now Loss :  1023


Model Init


In [8]:
### 3.1.7 in & not in

user_1 = {'name' : 'AI_BOT_1', 'email' : 'AI_BOT_1@abcdef.com', 'age' : 1}
user_2 = {'name' : 'AI_BOT_2', 'email' : 'AI_BOT_2abcdef.com', 'age' : 1}
user_3 = {'name' : 'AI_BOT_3', 'age' : 1}
if 'email' in user_1:
    if '@' not in user_1['email']:
        print('Email Address Error')
    else:
        print('Email: ' + user_1['email'])
else:
    print('No email')

if 'email' in user_2:
    if '@' not in user_2['email']:
        print('Email Address Error')
    else:
        print('Email: ' + user_2['email'])
else:
    print('No email')
    
if 'email' in user_3:
    if '@' not in user_3['email']:
        print('Email Address Error')
    else:
        print('Email: ' + user_3['email'])
else:
    print('No email')

Email: AI_BOT_1@abcdef.com
Email Address Error
No email


In [18]:
user_1 = {'name' : 'AI_BOT_1', 'email' : 'AI_BOT_1@abcdef.com', 'age' : 1}
user_2 = {'name' : 'AI_BOT_2', 'email' : 'AI_BOT_2abcdef.com', 'age' : 1}
user_3 = {'name' : 'AI_BOT_3', 'age' : 1}

if 'email' in user_1:
    if '@' not in user_1['email']:
        print('Email Address Error')
    else:
        print('Email: ', user_1['email'])
else:
    print('No email')

if 'email' in user_2:
    if '@' not in user_2['email']:
        print('Email Address Error')
    else:
        print('Email: ', user_2['email'])
else:
    print('No email')
    
if 'email' in user_3:
    if '@' not in user_3['email']:
        print('Email Address Error')
    else:
        print('Email: ', user_3['email'])
else:
    print('No email')

Email:  AI_BOT_1@abcdef.com
Email Address Error
No email


In [26]:
user_1 = {'name' : 'AI_BOT_1', 'email' : 'AI_BOT_1@abcdef.com', 'age' : 5}
user_2 = {'name' : 'AI_BOT_2', 'email' : 'AI_BOT_2@abcdef.com', 'age' : 23}
user_3 = {'name' : 'AI_BOT_3', 'email' : 'AI_BOT_3@abcdef.com'}

if 'age' in user_1:
    if user_1['age'] > 10:
        print('so young')
    else:
        print('oh baby')
else:
    print('how old are you?')
    
if 'age' in user_2:
    if user_2['age'] > 10:
        print('so young')
    else:
        print('oh baby')
else:
    print('how old are you?')
    
if 'age' in user_3:
    if user_3['age'] > 10:
        print('so young')
    else:
        print('oh baby')
else:
    print('how old are you?')
    


oh baby
so young
how old are you?


In [ ]:
#======================================풀어보자!
user_1 = {'name' : 'AI_BOT_1', 'email' : 'AI_BOT_1@abcdef.com', 'age' : 5}
user_2 = {'name' : 'AI_BOT_', 'email' : 'AI_BOT_2@abcdef.com', 'age' : 23}
user_3 = {'email' : 'AI_BOT_3@abcdef.com', 'age' : 42}

if 'name' in user_1:
    if

In [29]:
###one hot verxtor 구문으로 성별,유충을 숫자로 바꿔줄 수 있음
###0,1,2로 바꿨을 때 숫자는 크기를 가지고 있기 때문에, 1과 2는 2배의 차이가 나고 0과 1은 차이라고 할 수 는 없으나 차이가 있듯
###0,1,2로 바꿧을때의 리스크가 존재하고 연산과정에서 문제가 발생할 수 있음.
###one hot(1이란 값의 불을 켜주겠다, 핫스팟 처럼), vector 이 m, f, i 니까
###m 은 1, 0, 0
###f 는 0, 1, 0
###i 는 0, 0, 1

import numpy as np

#rows = ['M',0.455,0.365,0.095]
#rows = ['F',0.455,0.365,0.095]
rows = ['I',0.455,0.365,0.095]

data = np.zeros(6)
#zeros 는 버퍼 / 임시공간 이러한 공간을 만들어 주는 것임
print('data : \n', data)

data : 
 [0. 0. 0. 0. 0. 0.]


In [30]:
if rows[0] == 'M':
    data[0] = 1
elif rows[0] == 'F': 
    data[1] = 1
elif rows[0] == 'I': 
    data[2] = 1     

print(data)

[0. 0. 1. 0. 0. 0.]


In [31]:
data[3:] = rows[1:]
print(data)

[0.    0.    1.    0.455 0.365 0.095]


In [39]:
import numpy as np

rows_1 = ['M',0.455,0.365,0.095]
rows_2 = ['F',0.455,0.365,0.095]
rows_3 = ['I',0.455,0.365,0.095]

data_1 = np.zeros(6)
data_2 = np.zeros(6)
data_3 = np.zeros(6)
print('data_1 \n', data_1)
print('data_2 \n', data_2)
print('data_3 \n', data_3)
print('='*30)
if rows_1[0] == 'M':
    data_1[0] = 1
elif rows_1[0] == 'F':
    data_1[1] = 1
elif rows_1[0] == 'I':
    data_1[2] = 1

print('data_1 \n', data_1)

if rows_2[0] == 'M':
    data_2[0] = 1
elif rows_2[0] == 'F':
    data_2[1] = 1
elif rows_2[0] == 'I':
    data_2[2] = 1

print('data_2 \n', data_2)


if rows_3[0] == 'M':
    data_3[0] = 1
elif rows_3[0] == 'F':
    data_3[1] = 1
elif rows_3[0] == 'I':
    data_3[2] = 1

print('data_3 \n', data_3)

print('='*30)

data_1[3:] = rows_1 [1:]
print(data_1)
data_2[3:] = rows_2 [1:]
print(data_2)
data_3[3:] = rows_3 [1:]
print(data_3)

data_1 
 [0. 0. 0. 0. 0. 0.]
data_2 
 [0. 0. 0. 0. 0. 0.]
data_3 
 [0. 0. 0. 0. 0. 0.]
data_1 
 [1. 0. 0. 0. 0. 0.]
data_2 
 [0. 1. 0. 0. 0. 0.]
data_3 
 [0. 0. 1. 0. 0. 0.]
[1.    0.    0.    0.455 0.365 0.095]
[0.    1.    0.    0.455 0.365 0.095]
[0.    0.    1.    0.455 0.365 0.095]


In [ ]:

ID = input("Enter your ID")
age = input("Enter your Age as a Number.")

user = {'ID' : ID, 'age' : age}

if user['age'].isdigit() == True:
    user['age'] = int(user['age'])
    
    if user['age'] <= 15:
        print("Manager System : Sorry {}. ".format(user['ID']) + "You can't Enter.")
        teenager.append(user['ID'])
    else:
        print('{}, Have A Good Time.'.format(user['ID']))
else:
    print('Please, Enter your Age as Number.')


In [ ]:
##연습

teen = []

ID = input('Enter Your ID')
AGE = input.int('Enter Your AGE')

USER = {'ID' : ID, 'AGE' : AGE}

#if USER['age'].isdigit() == True:
#    user['age'] = int

if USER['age'] <= 15:
    print("SORRY. YOU CAN'T SEE")
else:
    print("HAVE A GOOD TIME")


In [1]:
teenager = []

ID = input('write your ID')
age = input('write your age')

user = {'ID': ID, 'age' : age}

if user['age'].isdigit() == True:
    user['age'] = int(user['age'])
    
    if user['age'] <= 15:
        print("no {} you can't enter".format(user['ID']))
        teenager.append(user['ID'])
    else:
        print("{}. good watching".format(user['ID']))
else:
    print('plz, write your age in number')

write your ID like
write your age 27


like. good watching


In [ ]:
#넷플릭스 teenager one more time!! 해보기!