In [20]:
###2_1_4
###딕셔너리 파트
###loc 는 평균값
###scale 는 표준편차
###input_cnt, output_cnt 는 변수이고, 수식에 들어가는 값 (신경망)
### 3개의 입력값을 받았을 때 1개의 값을 받는 코드를 만들어 준 것임

import numpy as np

input_cnt = 3
output_cnt = 1

###input_cnt, output_cnt = 3, 1 (이렇게 적기도 함)

input_x = [[0.12, 1.02, 4.1],[0.15,5.12,12.2]] 
#무작위 값임 =학습 데이터라고 부를 수 있음
#학습데이터 2개임^^ 아우 친절
label_y = [[5],[3]]
#종속변수 5와 3임
input_x_shape = np.array(input_x)
#넘파이에 맞는 매소드를 만들어줘야함
print(input_x_shape)
#리스트에서 어레이 함수로 바뀌었을 뿐 전혀 달라진 것이 없음
print("ㅡ"*30)
print("input_x_shape: ", input_x_shape.shape)
#shape은 모양이라는 뜻을 의미함, 몇컴마 몇이냐를 의미함
#2개의 행과 3개의 열로 이루어져있음(2,3)

theta_1 = np.random.normal(loc = 0, scale = 1, size = [input_cnt, output_cnt]) 
print("theta_1_shape: ", theta_1.shape)
theta_0 = np.random.normal(loc = 0, scale = 1, size = [output_cnt])
#신경망을 만들때 다시 한 번 구조를 알려주신다심.


print(theta_1)
#3개의 값이 한 열로 나옴 [3,1] 의 크기로 입력을 한 것이기 때문
print('ㅡ'*30)
print(theta_0)

y_hat = np.matmul(input_x, theta_1) + theta_0 
# 중요!!!!!!!!!!! matmul(중요함!) 안에 input_x 학습데이터와, theta_1 이 들어가 있음
#y햇은 행열연산을 빠르게 진행시켜줄 수 있는 함수임
print("y_hat : ", y_hat)
#데이터를 2개 넣엇기 때문에 라벨값과 곱해진 결과 하나하나가 출력되어 2개가 나옴

print(label_y)
#랜덤으로 구한 값이라서 -1과 5 -0과 3처럼 차이가 큼, 이것을 더 정확하게 학습시키는 공부를 진행할 것임

[[ 0.12  1.02  4.1 ]
 [ 0.15  5.12 12.2 ]]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
input_x_shape:  (2, 3)
theta_1_shape:  (3, 1)
[[-1.70257403]
 [-1.06796299]
 [ 0.55744104]]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
[-0.26048893]
y_hat :  [[0.73138819]
 [0.8169351 ]]
[[5], [3]]


In [21]:
###mse
print(y_hat[0])
print(y_hat[1])
print(label_y[0])
print(label_y[1])
print('ㅡ'*30)

a = (y_hat[0]-label_y[0])**2
b = (y_hat[1]-label_y[1])**2
print('NOW PM')
#세타원 세타제로를 파라미터라고 부름
print('theta_0 : ', theta_0)
print('theta_1 : ', theta_1)
print('ㅡ'*30)
###무작위 값으로 세타를 설정했기 때문에 random, 큰 값이 나올 수 밖에 없음(작은 값이 나와야 좋음)

mse = (a+b)/2
print('mse : ', mse)

[0.73138819]
[0.8169351]
[5]
[3]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
NOW PM
theta_0 :  [-0.26048893]
theta_1 :  [[-1.70257403]
 [-1.06796299]
 [ 0.55744104]]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
mse :  [11.4934096]


In [23]:
import numpy as np

input_cnt = 3
output_cnt = 1

input_x = [[0.12, 1.02, 4.1],[0.15,5.12,12.2]] 
label_y = [[5],[3]]
input_x_shape = np.array(input_x)
print("input_x_shape: ", input_x_shape.shape)

theta_1 = np.random.normal(loc = 0, scale = 1, size = [input_cnt, output_cnt]) 
print("theta_1_shape: ", theta_1.shape)
theta_0 = np.random.normal(0, 1, [output_cnt])

#===========================================
parameter = {'w' : theta_1, 'b' : theta_0}
#weight 의 앞자 w, b는 편향 biss
#w를 적었을 때 theta_1값이 나와라~
y_hat = np.matmul(input_x, parameter['w']) + parameter['b'] 
#파라미터 안의 w를 부르는건데 w가 아닌 w가 가진 값 가져와!
#이러한 방식으로 딕셔너리를 사용할 수 있음
#===========================================
print(y_hat)

input_x_shape:  (2, 3)
theta_1_shape:  (3, 1)
[[ 4.15913702]
 [12.0394752 ]]


In [24]:
print(parameter.values())
print(parameter.keys())

dict_values([array([[-0.33178405],
       [-0.28529023],
       [ 1.11851625]]), array([-0.09596949])])
dict_keys(['w', 'b'])


In [25]:
#lossFunction 손실

parameter = {'b' : 0.011}
input_cnt = 10 #독립변수
output_cnt = 1 #종속변수
print(parameter.get('w',np.random.normal(loc = 0, 
                                         scale = 1, 
                                         size = [input_cnt, output_cnt])))

#get함수는 내가 원하는 키값이 없을 때 사용한다는 등, 가볍게 알고 넘어가면된데

[[ 0.58519465]
 [-1.63627513]
 [ 1.72814337]
 [-0.14116499]
 [ 1.13201614]
 [-2.24740117]
 [ 1.84123701]
 [ 0.65197409]
 [ 0.01428262]
 [-1.62068896]]


In [ ]:
parameter = {'b' : 0.011, 'w' : 1.151}
input_cnt = 10
output_cnt = 1
print(parameter.get('w',np.random.normal(loc = 0, 
                                         scale = 1, 
                                         size = [input_cnt, output_cnt])))