In [ ]:
#함수
#def = define
#return 을 사용하는 경우 res를 밖으로 빼줄 수 있음 (물론 print 만 사용할 수도 있음) ->연산결과를 또 사용할 수 있음
#1,2확인

In [24]:
import numpy as np

In [3]:
#1

def my_sum(a,b):
    res = a+b
    return res

res = my_sum(10,20)
print(res)

30


In [4]:
#2

def my_sum(a,b):
    res = a+b
    print(res)

res = my_sum(10,20)
print(res)

30
None


In [2]:
def sum(a,b):
    res = a+b
    print(res)
    return res
res = sum(10,20)
print(res)

30
30


In [8]:
#리그오브레전드 시나리오
name = '징크스'
hp = 768
damage = 80

print("{0} 소환사의 협곡에 오신 것을 환영합니다.".format(name))
print("hp : {0}, damage : {1}".format(hp, damage))

징크스 소환사의 협곡에 오신 것을 환영합니다.
hp : 768, damage : 80


In [9]:
name_s = '스웨인'
hp_s = 860
damage_s = 55

print("{0} 소환사의 협곡에 오신 것을 환영합니다.".format(name_s))
print("hp : {0}, damage : {1}".format(hp_s, damage_s))

스웨인 소환사의 협곡에 오신 것을 환영합니다.
hp : 860, damage : 55


In [10]:
def attack(name, location, damage):
    print("{0} : 공격을 {1} 뱡향으로 실행하였습니다. [Damage : {2}]".\
          format(name, location, damage))


In [12]:
attack(name, "왼쪽", damage)
attack(name_s, "왼쪽", damage_s)

징크스 : 공격을 왼쪽 뱡향으로 실행하였습니다. [Damage : 80]
스웨인 : 공격을 왼쪽 뱡향으로 실행하였습니다. [Damage : 55]


In [13]:
def game_system():
    print("<Game System>")

In [14]:
def attack(name, location, damage):
    game_system()
    print("{0} : 공격을 {1} 뱡향으로 실행하였습니다. [Damage : {2}]".\
          format(name, location, damage))

In [15]:
attack(name, "왼쪽", damage)
attack(name_s, "왼쪽", damage_s)

<Game System>
징크스 : 공격을 왼쪽 뱡향으로 실행하였습니다. [Damage : 80]
<Game System>
스웨인 : 공격을 왼쪽 뱡향으로 실행하였습니다. [Damage : 55]


In [21]:
def main_exec():
    import_data() #데이터를 불러오는 기능
    model_init() #가중치나 편향값을 초기화
    train_and_test() #학습과 테스트를 수행하는 함수

In [ ]:
y_hat = theta_0 + theta_1*x

In [25]:
#이 함수는 파라미터(가중치[세타1], 편향[세타0])을 초기화 시켜주는 함수입니다.
RND_mean = 0
RND_std = 1 #RND는 랜덤함수의 약자임

input_cnt = 10 #독립변수의 수
output_cnt = 1 #종속변수의 수(변하지 않음)

def model_init():
    global weight, bias #전역변수, 다른 함수에서는 이 이름을 사용할 수 없음.
    weight = np.random.normal(RND_mean, RND_std), [input_cnt, output_cnt]  #weight이나 bias에는 무작위 값을 넣는다
    bias = np.random.normal(RND_mean, RND_std, [output_cnt])
    return weight, bias
model_init()

((-0.2799141997510614, [10, 1]), array([0.87482365]))

In [26]:
weight

(-0.2799141997510614, [10, 1])

In [27]:
bias

array([0.87482365])

In [28]:
def main_exec():
   # import_data() #데이터를 불러오는 기능
    model_init() #가중치나 편향값을 초기화
   # train_and_test() #학습과 테스트를 수행하는 함수

In [29]:
main_exec()

In [30]:
weight

(0.580203562246681, [10, 1])

In [118]:
#import_data 함수를 만들어보기 / 이 함수는 데이터를 불러오고, 원 핫 벡터 처리를 수행한다.

import csv
import numpy as np

with open('abalone_mini.csv') as csvfile:
    csvreader = csv.reader(csvfile)
    #print(csvreader)
    rows = []
    for row in csvreader:
        rows.append(row)

#print(rows)

data = np.zeros([5,11])
#print(data)

for row in enumerate(rows):
    if row[0] == 'I' :data [n,0] = 1



data = np.zeros([5,11])
#print(data)

#for row in rows:
    #print(row)
#for row in enumerate(rows):
    #print(row)
    #enumerate는 인덱스 번호가 같이 와 있음
for n,row in enumerate(rows):    
    if row[0] == 'I' : data [n,0] = 1
    if row[0] == 'M' : data [n,1] = 1
    if row[0] == 'F' : data [n,2] = 1
        
    data[n, 3:] = row[1:]
    
print(data)


[[ 0.      1.      0.      0.455   0.365   0.095   0.514   0.2245  0.101
   0.15   15.    ]
 [ 0.      1.      0.      0.35    0.265   0.09    0.2255  0.0995  0.0485
   0.07    7.    ]
 [ 0.      0.      1.      0.53    0.42    0.135   0.677   0.2565  0.1415
   0.21    9.    ]
 [ 0.      1.      0.      0.44    0.365   0.125   0.516   0.2155  0.114
   0.155  10.    ]
 [ 1.      0.      0.      0.33    0.255   0.08    0.205   0.0895  0.0395
   0.055   7.    ]]


In [136]:
def import_data():
    import csv
    import numpy as np
    
    with open('abalone_mini.csv') as csvfile:
        csvreader = csv.reader(csvfile)
        #print(csvreader)
        rows = []
        for row in csvreader:
            rows.append(row)
            
    data = np.zeros([5,11])
    
    for n, row in enumerate(rows):
        if row[0] == 'I' :data [n,0] = 1
        if row[0] == 'M' : data [n,1] = 1
        if row[0] == 'F' : data [n,2] = 1
        
        data[n, 3:] = row[1:]
        
    return import_data

def model_init():
    global weight, bias #전역변수, 다른 함수에서는 이 이름을 사용할 수 없음.
    weight = np.random.normal(RND_mean, RND_std), [input_cnt, output_cnt]  #weight이나 bias에는 무작위 값을 넣는다
    bias = np.random.normal(RND_mean, RND_std, [output_cnt])
    return weight, bias

def main_exec():
    import_data() #데이터를 불러오는 기능
    model_init() #가중치나 편향값을 초기화
   # train_and_test() #학습과 테스트를 수행하는 함수

main_exec()

In [137]:
import csv
import numpy as np
    
def import_data():
    global data
    with open('abalone_mini.csv') as csvfile:
        csvreader = csv.reader(csvfile)
        #print(csvreader)
        rows = []
        for row in csvreader:
            rows.append(row)
            
    data = np.zeros([5,11])
    
    for n,row in enumerate(rows): #enunmerate를 사용할때는 변수를 2개 사용해야함
        if row[0] == 'I' :data [n,0] = 1
        elif row[0] == 'M' : data [n,1] = 1
        elif row[0] == 'F' : data [n,2] = 1
        
        data[n, 3:] = row[1:]

In [138]:
import_data()

In [139]:
data

array([[ 0.    ,  1.    ,  0.    ,  0.455 ,  0.365 ,  0.095 ,  0.514 ,
         0.2245,  0.101 ,  0.15  , 15.    ],
       [ 0.    ,  1.    ,  0.    ,  0.35  ,  0.265 ,  0.09  ,  0.2255,
         0.0995,  0.0485,  0.07  ,  7.    ],
       [ 0.    ,  0.    ,  1.    ,  0.53  ,  0.42  ,  0.135 ,  0.677 ,
         0.2565,  0.1415,  0.21  ,  9.    ],
       [ 0.    ,  1.    ,  0.    ,  0.44  ,  0.365 ,  0.125 ,  0.516 ,
         0.2155,  0.114 ,  0.155 , 10.    ],
       [ 1.    ,  0.    ,  0.    ,  0.33  ,  0.255 ,  0.08  ,  0.205 ,
         0.0895,  0.0395,  0.055 ,  7.    ]])

In [140]:
def model_init():
    global weight, bias #전역변수, 다른 함수에서는 이 이름을 사용할 수 없음.
    weight = np.random.normal(RND_mean, RND_std, [input_cnt, output_cnt])  #weight이나 bias에는 무작위 값을 넣는다
    bias = np.random.normal(RND_mean, RND_std, [output_cnt])
    return weight, bias


In [141]:
model_init()

(array([[-1.16130302],
        [ 1.57084236],
        [ 1.47372493],
        [-0.65384562],
        [ 0.09745833],
        [ 1.81478277],
        [-0.67030949],
        [-0.5916598 ],
        [ 0.06705058],
        [ 1.66715103]]),
 array([1.27565237]))

In [142]:
def main_exec():
    import_data() #데이터를 불러오는 기능
    model_init() #가중치나 편향값을 초기화
   # train_and_test() #학습과 테스트를 수행하는 함수

In [143]:
main_exec()

In [144]:
weight

array([[ 0.36916275],
       [ 0.61891571],
       [-1.18930382],
       [-0.57523968],
       [-0.19792859],
       [ 0.82867192],
       [-0.47753564],
       [ 0.51216108],
       [ 1.456605  ],
       [ 0.98748334]])

In [145]:
data

array([[ 0.    ,  1.    ,  0.    ,  0.455 ,  0.365 ,  0.095 ,  0.514 ,
         0.2245,  0.101 ,  0.15  , 15.    ],
       [ 0.    ,  1.    ,  0.    ,  0.35  ,  0.265 ,  0.09  ,  0.2255,
         0.0995,  0.0485,  0.07  ,  7.    ],
       [ 0.    ,  0.    ,  1.    ,  0.53  ,  0.42  ,  0.135 ,  0.677 ,
         0.2565,  0.1415,  0.21  ,  9.    ],
       [ 0.    ,  1.    ,  0.    ,  0.44  ,  0.365 ,  0.125 ,  0.516 ,
         0.2155,  0.114 ,  0.155 , 10.    ],
       [ 1.    ,  0.    ,  0.    ,  0.33  ,  0.255 ,  0.08  ,  0.205 ,
         0.0895,  0.0395,  0.055 ,  7.    ]])

In [146]:
def load_dataset():
    global data
    with open('abalone_mini.csv') as csvfile:
        csvreader = csv.reader(csvfile)
        #print(csvreader)
        rows = []
        for row in csvreader:
            rows.append(row)
            
    data = np.zeros([5,11])
    
    for n,row in enumerate(rows): #enunmerate를 사용할때는 변수를 2개 사용해야함???
        if row[0] == 'I' :data [n,0] = 1
        elif row[0] == 'M' : data [n,1] = 1
        elif row[0] == 'F' : data [n,2] = 1
        
        data[n, 3:] = row[1:]

In [147]:
import numpy as np
import csv
load_dataset()
data

array([[ 0.    ,  1.    ,  0.    ,  0.455 ,  0.365 ,  0.095 ,  0.514 ,
         0.2245,  0.101 ,  0.15  , 15.    ],
       [ 0.    ,  1.    ,  0.    ,  0.35  ,  0.265 ,  0.09  ,  0.2255,
         0.0995,  0.0485,  0.07  ,  7.    ],
       [ 0.    ,  0.    ,  1.    ,  0.53  ,  0.42  ,  0.135 ,  0.677 ,
         0.2565,  0.1415,  0.21  ,  9.    ],
       [ 0.    ,  1.    ,  0.    ,  0.44  ,  0.365 ,  0.125 ,  0.516 ,
         0.2155,  0.114 ,  0.155 , 10.    ],
       [ 1.    ,  0.    ,  0.    ,  0.33  ,  0.255 ,  0.08  ,  0.205 ,
         0.0895,  0.0395,  0.055 ,  7.    ]])

In [148]:
#역전파!
def forward_neuralnet(x):
    y = np.matmul(x,weight) + bias #행열곱하는거라고 들어버렷다... 뭐가 맞는 걸까
    #x는 어디서 가져올까? 위에서 전역변수! 를 만들었기 때문에 y를 만들어 볼 수 있음
    return y

In [149]:
forward_neuralnet(data[:,:-1])

array([[ 0.2779756 ],
       [ 0.27230374],
       [-1.49433375],
       [ 0.32977312],
       [ 0.00449431]])

In [150]:
data[:, :-1]

array([[0.    , 1.    , 0.    , 0.455 , 0.365 , 0.095 , 0.514 , 0.2245,
        0.101 , 0.15  ],
       [0.    , 1.    , 0.    , 0.35  , 0.265 , 0.09  , 0.2255, 0.0995,
        0.0485, 0.07  ],
       [0.    , 0.    , 1.    , 0.53  , 0.42  , 0.135 , 0.677 , 0.2565,
        0.1415, 0.21  ],
       [0.    , 1.    , 0.    , 0.44  , 0.365 , 0.125 , 0.516 , 0.2155,
        0.114 , 0.155 ],
       [1.    , 0.    , 0.    , 0.33  , 0.255 , 0.08  , 0.205 , 0.0895,
        0.0395, 0.055 ]])

In [151]:
def forward_postproc(output, y):
    print("output : ", output)
    print("y : ", y)
    diff = output - y #output인 예측값과 실제 종속변수y값을 뺀 값 diff
    print("diff : ", diff)
    square = np.square(diff) #square 제곱하는 거
    print("square : ", square)
    loss = np.mean(square) #mean 평균 구하는 거
    print("loss : ", loss)
    
    return loss

In [152]:
forward_postproc(forward_neuralnet(data[:,:-1]), data[:, -1:])

output :  [[ 0.2779756 ]
 [ 0.27230374]
 [-1.49433375]
 [ 0.32977312]
 [ 0.00449431]]
y :  [[15.]
 [ 7.]
 [ 9.]
 [10.]
 [ 7.]]
diff :  [[-14.7220244 ]
 [ -6.72769626]
 [-10.49433375]
 [ -9.67022688]
 [ -6.99550569]]
square :  [[216.73800233]
 [ 45.26189703]
 [110.13104083]
 [ 93.51328797]
 [ 48.93709979]]
loss :  102.91626558953696


102.91626558953696

In [153]:
def run_train(x,y):
    output = forward_neuralnet(x)
    cost = forward_postproc(output, y)
    
    return output, cost


In [154]:
run_train(data[:,:-1], data[:,-1:])

output :  [[ 0.2779756 ]
 [ 0.27230374]
 [-1.49433375]
 [ 0.32977312]
 [ 0.00449431]]
y :  [[15.]
 [ 7.]
 [ 9.]
 [10.]
 [ 7.]]
diff :  [[-14.7220244 ]
 [ -6.72769626]
 [-10.49433375]
 [ -9.67022688]
 [ -6.99550569]]
square :  [[216.73800233]
 [ 45.26189703]
 [110.13104083]
 [ 93.51328797]
 [ 48.93709979]]
loss :  102.91626558953696


(array([[ 0.2779756 ],
        [ 0.27230374],
        [-1.49433375],
        [ 0.32977312],
        [ 0.00449431]]),
 102.91626558953696)